-- =====================================================
-- نبض (Nabth) - Schema for Medical Appointment App
-- Run this SQL in your Supabase SQL Editor (Project: ydobpremnsiggeohwhae)
-- =====================================================

-- ---------- speciality table ----------
create table if not exists public.speciality (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text not null,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- ---------- doctor table ----------
create table if not exists public.doctor (
  id bigint generated by default as identity primary key,
  full_name text not null,
  image text not null,
  description text,
  gender text,
  speciality bigint references public.speciality(id) on delete set null,
  price double precision default 0,
  experience_number int default 0,
  rating_number int default 0,
  patient_number int default 0,
  availability text,
  status text default 'offline',
  created_at timestamptz default now()
);

-- ---------- patient table ----------
create table if not exists public.patient (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text,
  phone_number bigint,
  gender text,
  age int,
  detail text,
  created_at timestamptz default now()
);

-- ---------- appointment table ----------
create table if not exists public.appointment (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  doctor_id bigint references public.doctor(id) on delete set null,
  patient_id bigint references public.patient(id) on delete set null,
  consultation_type text,
  consultation_fee text,
  date text,
  time text,
  status text default 'pending',
  created_at timestamptz default now()
);

-- =====================================================
-- Row Level Security (RLS)
-- =====================================================

alter table public.speciality enable row level security;
alter table public.doctor enable row level security;
alter table public.patient enable row level security;
alter table public.appointment enable row level security;

-- Public read access for specialities and doctors
create policy "speciality_read_all"
  on public.speciality for select using (true);
create policy "doctor_read_all"
  on public.doctor for select using (true);

-- Patients can insert their own records
create policy "patient_insert_own"
  on public.patient for insert with check (true);
create policy "patient_read_own"
  on public.patient for select using (true);

-- Appointments: authenticated users manage their own
create policy "appointment_insert_own"
  on public.appointment for insert with check (auth.uid() = user_id);
create policy "appointment_read_own"
  on public.appointment for select using (auth.uid() = user_id);
create policy "appointment_update_own"
  on public.appointment for update using (auth.uid() = user_id);

-- =====================================================
-- Sample data (optional)
-- =====================================================

insert into public.speciality (name, icon, is_active) values
  ('طب الأسنان', 'https://api.iconify.design/mdi:tooth.svg', true),
  ('طب العيون', 'https://api.iconify.design/mdi:eye.svg', true),
  ('أمراض القلب', 'https://api.iconify.design/mdi:heart-pulse.svg', true),
  ('الأنف والأذن والحنجرة', 'https://api.iconify.design/mdi:ear-hearing.svg', true),
  ('طب الأطفال', 'https://api.iconify.design/mdi:baby-face-outline.svg', true),
  ('طب الأعصاب', 'https://api.iconify.design/mdi:brain.svg', true),
  ('الجلدية', 'https://api.iconify.design/mdi:hand-heart.svg', true),
  ('النساء والتوليد', 'https://api.iconify.design/mdi:human-pregnant.svg', true);

insert into public.doctor
  (full_name, image, description, gender, speciality, price,
   experience_number, rating_number, patient_number, availability, status)
values
  ('د. أحمد خالد', 'https://randomuser.me/api/portraits/men/32.jpg',
   'طبيب أسنان متخصص في طب الأسنان التجميلي والعلاجي.', 'Male', 1, 80,
   10, 5, 1200, 'morning', 'online'),
  ('د. سارة محمود', 'https://randomuser.me/api/portraits/women/44.jpg',
   'استشارية طب وجراحة العيون وعلاج أمراض الشبكية.', 'Female', 2, 100,
   12, 5, 900, 'afternoon', 'online'),
  ('د. محمد عبد الله', 'https://randomuser.me/api/portraits/men/45.jpg',
   'استشاري أمراض القلب والقسطرة العلاجية.', 'Male', 3, 150,
   20, 4, 2000, 'morning', 'online'),
  ('د. نورة العلي', 'https://randomuser.me/api/portraits/women/65.jpg',
   'أخصائية الأنف والأذن والحنجرة وجراحات السمع.', 'Female', 4, 90,
   8, 4, 700, 'night', 'online'),
  ('د. ليلى حسن', 'https://randomuser.me/api/portraits/women/24.jpg',
   'أخصائية طب الأطفال ورعاية حديثي الولادة.', 'Female', 5, 70,
   6, 4, 1500, 'morning', 'online'),
  ('د. عمر فؤاد', 'https://randomuser.me/api/portraits/men/68.jpg',
   'استشاري طب الأعصاب وعلاج الصداع والصرع.', 'Male', 6, 120,
   15, 5, 850, 'afternoon', 'online'),
  ('د. هدى سليم', 'https://randomuser.me/api/portraits/women/57.jpg',
   'أخصائية الأمراض الجلدية والتجميل.', 'Female', 7, 85,
   9, 4, 1100, 'night', 'online');
